version: "3.9"
services:
  redis:
    image: redis:7
    ports: ["6379:6379"]

  api:
    build:
      context: ./app
      dockerfile: Dockerfile.dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    ports: ["8000:8000"]
    depends_on: [redis]

