apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: demo
spec:
  selector: { app: api }
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer  # Sur Docker Desktop/Minikube: NodePort/port-forward si besoin
